services:
  postgres:
    image: postgres:16.2-alpine
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=anoop
      - POSTGRES_DB=simple-bank
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U anoop -d simple-bank"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://anoop:root@postgres:5432/simple-bank?sslmode=disable
      - DB_DRIVER=postgres
      - SERVER_ADDRESS=localhost:8080
    depends_on:
      postgres:
        condition: service_healthy
    
